# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_id', models.IntegerField()),
                ('uname', models.TextField()),
                ('psk', models.TextField()),
                ('hos_code', models.CharField(max_length=2)),
                ('mail_id', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
    ]
