# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField()),
                ('item_id', models.TextField()),
                ('price', models.IntegerField()),
                ('item_name', models.TextField()),
            ],
        ),
    ]
