# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0002_menu_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField()),
                ('min_order_val', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
