# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0003_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='psk',
            field=models.TextField(default='cd414f77d77bc893dbfd9b39f90c9a182366fd20d7ab8e3fe29f82c27fe3b7db'),
            preserve_default=False,
        ),
    ]
